[package]
name = "rusty-chip8"
version = "0.1.0"
authors = ["Christian Engen <chris.a.engen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
